- name: ensure pip root
  tags:
    - pip
  file:
    path: ~/.config/pip
    state: directory
    follow: yes
    recurse: yes

- name: ensure pip config
  tags:
    - pip
  vars:
    timeout: 600
    mirror: "{{ pyenv_pip_mirror }}"
  template:
    src: ../templates/pip.conf.j2
    dest: ~/.config/pip/pip.conf
